name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/cmake-configure@prerel1

    - name: CMake generate
      run: |
        cmake --version
        cmake . -B./build

    - name: To ./build
      run: cd ./build

    - name: Make executable
      run: make

    - name: Run main.cpp
      run: ./fancy
