name: C/C++ CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/cmake-configure@prerel1

    - name: Check CMake version
      run: cmake --version
    - name: CMake build
      run: cmake . -B./build
    - name: To ./build
      run: cd ./build
    - name: Make
      run: make
    - name: Run main.cpp
      run: ./fancy

