name: C/C++ CI
  

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/cmake-configure@prerel1
    - name: cmake build
      run: cmake . -B./build
    - name: to ./build
      run: cd ./build
    - name: make
      run: make
